/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mikec.shedule.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.YearMonth;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import mikec.shedule.controller.LabelController;
import mikec.shedule.controller.RecordController;
import mikec.shedule.model.Label;
import mikec.shedule.model.User;
import mikec.shedule.util.BaseException;

public class SheduleTable extends javax.swing.JFrame {    
    
    JComboBox<Label> cmbLabels;       
    RecordController recordController;
            
    public SheduleTable(Integer year, Integer month) throws BaseException {
        initComponents();
        recordController = new RecordController();
       
        YearMonth obj;
        obj = YearMonth.of(year, month);
        int numOfDaysInMoth = obj.lengthOfMonth();		

        LabelController labelController = new LabelController();
        List<Label> labels = labelController.read();
        cmbLabels = new JComboBox<>();
        cmbLabels.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                JOptionPane.showMessageDialog(rootPane, cmbLabels.getSelectedItem());
            }
        });
        DefaultComboBoxModel<Label> defaultCbModel = new DefaultComboBoxModel<>();
        defaultCbModel.addElement(new Label("-", ""));
        labels.forEach(s -> {
            defaultCbModel.addElement(s);
        });
        
        cmbLabels.setModel(defaultCbModel);
        cmbLabels.setSelectedIndex(0);

        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("");

        for (int i = 1; i <= numOfDaysInMoth; i++) {
            defaultTableModel.addColumn(i);
        }

        tblShedule.setModel(defaultTableModel);
        JTextField t = new JTextField();
        tblShedule.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(t));

        for (int i = 1; i < numOfDaysInMoth; i++) {
            tblShedule.getColumnModel().getColumn(i).setCellEditor(new DefaultCellEditor(cmbLabels));
        }
        
//        List<User> usersInMonth = recordController.getUsersForMonth(year, month);
//        for (User u : usersInMonth) {
//            Object[] niz = new Object[numOfDaysInMoth+1];
//            niz[0] = u.getPerson();
//            for (int i = 1; i < numOfDaysInMoth+1; i++) {
//               
//                    niz[i] = labels.get(z%2);
//                
//                
//            }
//
//            defaultTableModel.addRow(niz);
//        }

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblShedule = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblShedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblShedule);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblShedule;
    // End of variables declaration//GEN-END:variables
}
